export interface LocalGovernment {
  id: string;
  name: string;
  code: string;
}

export interface State {
  id: string;
  name: string;
  code: string;
  localGovernments: LocalGovernment[];
}

export const NIGERIA_STATES: State[] = [
  {
    id: 'abia',
    name: 'Abia',
    code: 'AB',
    localGovernments: [
      { id: 'aba-north', name: 'Aba North', code: 'ABN' },
      { id: 'aba-south', name: 'Aba South', code: 'ABS' },
      { id: 'arochukwu', name: 'Arochukwu', code: 'ARO' },
      { id: 'bende', name: 'Bende', code: 'BEN' },
      { id: 'ikwuano', name: 'Ikwuano', code: 'IKW' },
      { id: 'isiala-ngwa-north', name: 'Isiala Ngwa North', code: 'INN' },
      { id: 'isiala-ngwa-south', name: 'Isiala Ngwa South', code: 'INS' },
      { id: 'isuikwuato', name: 'Isuikwuato', code: 'ISU' },
      { id: 'item', name: 'Item', code: 'ITM' },
      { id: 'iwuanyanwu', name: 'Iwuanyanwu', code: 'IWU' },
      { id: 'nkwerre', name: 'Nkwerre', code: 'NKW' },
      { id: 'obi-ngwa', name: 'Obi Ngwa', code: 'OBN' },
      { id: 'ohafia', name: 'Ohafia', code: 'OHA' },
      { id: 'osisioma', name: 'Osisioma', code: 'OSI' },
      { id: 'ugwunagbo', name: 'Ugwunagbo', code: 'UGW' },
      { id: 'ukwa-east', name: 'Ukwa East', code: 'UKE' },
      { id: 'ukwa-west', name: 'Ukwa West', code: 'UKW' },
      { id: 'umuahia-north', name: 'Umuahia North', code: 'UMN' },
      { id: 'umuahia-south', name: 'Umuahia South', code: 'UMS' },
      { id: 'umu-nneochi', name: 'Umu Nneochi', code: 'UNN' }
    ]
  },
  {
    id: 'adamawa',
    name: 'Adamawa',
    code: 'AD',
    localGovernments: [
      { id: 'demsa', name: 'Demsa', code: 'DEM' },
      { id: 'fufure', name: 'Fufure', code: 'FUF' },
      { id: 'ganye', name: 'Ganye', code: 'GAN' },
      { id: 'gayuk', name: 'Gayuk', code: 'GAY' },
      { id: 'gombi', name: 'Gombi', code: 'GOM' },
      { id: 'grie', name: 'Grie', code: 'GRI' },
      { id: 'hong', name: 'Hong', code: 'HON' },
      { id: 'jada', name: 'Jada', code: 'JAD' },
      { id: 'lamurde', name: 'Lamurde', code: 'LAM' },
      { id: 'madagali', name: 'Madagali', code: 'MAD' },
      { id: 'maiha', name: 'Maiha', code: 'MAI' },
      { id: 'mayo-belwa', name: 'Mayo Belwa', code: 'MBE' },
      { id: 'michika', name: 'Michika', code: 'MIC' },
      { id: 'mubi-north', name: 'Mubi North', code: 'MUN' },
      { id: 'mubi-south', name: 'Mubi South', code: 'MUS' },
      { id: 'numan', name: 'Numan', code: 'NUM' },
      { id: 'shelleng', name: 'Shelleng', code: 'SHE' },
      { id: 'song', name: 'Song', code: 'SON' },
      { id: 'toungo', name: 'Toungo', code: 'TOU' },
      { id: 'yola-north', name: 'Yola North', code: 'YON' },
      { id: 'yola-south', name: 'Yola South', code: 'YOS' }
    ]
  },
  {
    id: 'akwa-ibom',
    name: 'Akwa Ibom',
    code: 'AK',
    localGovernments: [
      { id: 'abak', name: 'Abak', code: 'ABA' },
      { id: 'eastern-obolo', name: 'Eastern Obolo', code: 'EOB' },
      { id: 'eket', name: 'Eket', code: 'EKE' },
      { id: 'esit-eket', name: 'Esit Eket', code: 'ESE' },
      { id: 'essien-udim', name: 'Essien Udim', code: 'ESU' },
      { id: 'etim-ekpo', name: 'Etim Ekpo', code: 'ETE' },
      { id: 'etinan', name: 'Etinan', code: 'ETI' },
      { id: 'ibeno', name: 'Ibeno', code: 'IBE' },
      { id: 'ibesikpo-asutan', name: 'Ibesikpo Asutan', code: 'IBA' },
      { id: 'ibiono-ibom', name: 'Ibiono-Ibom', code: 'IBI' },
      { id: 'ika', name: 'Ika', code: 'IKA' },
      { id: 'ikono', name: 'Ikono', code: 'IKO' },
      { id: 'ikot-abasi', name: 'Ikot Abasi', code: 'IKT' },
      { id: 'ikot-ekpene', name: 'Ikot Ekpene', code: 'IKE' },
      { id: 'ini', name: 'Ini', code: 'INI' },
      { id: 'itu', name: 'Itu', code: 'ITU' },
      { id: 'mbo', name: 'Mbo', code: 'MBO' },
      { id: 'mkpat-enin', name: 'Mkpat-Enin', code: 'MKP' },
      { id: 'nsit-atai', name: 'Nsit-Atai', code: 'NSA' },
      { id: 'nsit-ibom', name: 'Nsit-Ibom', code: 'NSI' },
      { id: 'nsit-ubium', name: 'Nsit-Ubium', code: 'NSU' },
      { id: 'obot-akara', name: 'Obot Akara', code: 'OBA' },
      { id: 'okobo', name: 'Okobo', code: 'OKO' },
      { id: 'onna', name: 'Onna', code: 'ONN' },
      { id: 'oron', name: 'Oron', code: 'ORO' },
      { id: 'oruk-anam', name: 'Oruk Anam', code: 'ORA' },
      { id: 'udung-uko', name: 'Udung-Uko', code: 'UDU' },
      { id: 'ukanafun', name: 'Ukanafun', code: 'UKA' },
      { id: 'uruan', name: 'Uruan', code: 'URU' },
      { id: 'urue-offong-oruko', name: 'Urue-Offong/Oruko', code: 'URO' },
      { id: 'uyo', name: 'Uyo', code: 'UYO' }
    ]
  },
  {
    id: 'anambra',
    name: 'Anambra',
    code: 'AN',
    localGovernments: [
      { id: 'aguata', name: 'Aguata', code: 'AGU' },
      { id: 'anambra-east', name: 'Anambra East', code: 'ANE' },
      { id: 'anambra-west', name: 'Anambra West', code: 'ANW' },
      { id: 'anaocha', name: 'Anaocha', code: 'ANA' },
      { id: 'awka-north', name: 'Awka North', code: 'AWN' },
      { id: 'awka-south', name: 'Awka South', code: 'AWS' },
      { id: 'ayamelum', name: 'Ayamelum', code: 'AYA' },
      { id: 'dunukofia', name: 'Dunukofia', code: 'DUN' },
      { id: 'ekwusigo', name: 'Ekwusigo', code: 'EKW' },
      { id: 'idemili-north', name: 'Idemili North', code: 'IDN' },
      { id: 'idemili-south', name: 'Idemili South', code: 'IDS' },
      { id: 'ihiala', name: 'Ihiala', code: 'IHI' },
      { id: 'njikoka', name: 'Njikoka', code: 'NJI' },
      { id: 'nnewi-north', name: 'Nnewi North', code: 'NNN' },
      { id: 'nnewi-south', name: 'Nnewi South', code: 'NNS' },
      { id: 'ogbaru', name: 'Ogbaru', code: 'OGB' },
      { id: 'onitsha-north', name: 'Onitsha North', code: 'ONI' },
      { id: 'onitsha-south', name: 'Onitsha South', code: 'ONS' },
      { id: 'orumba-north', name: 'Orumba North', code: 'ORN' },
      { id: 'orumba-south', name: 'Orumba South', code: 'ORS' },
      { id: 'oyi', name: 'Oyi', code: 'OYI' }
    ]
  },
  {
    id: 'bauchi',
    name: 'Bauchi',
    code: 'BA',
    localGovernments: [
      { id: 'alkaleri', name: 'Alkaleri', code: 'ALK' },
      { id: 'bauchi', name: 'Bauchi', code: 'BAU' },
      { id: 'bogoro', name: 'Bogoro', code: 'BOG' },
      { id: 'damban', name: 'Damban', code: 'DAM' },
      { id: 'darazo', name: 'Darazo', code: 'DAR' },
      { id: 'dass', name: 'Dass', code: 'DAS' },
      { id: 'gamawa', name: 'Gamawa', code: 'GAM' },
      { id: 'ganjuwa', name: 'Ganjuwa', code: 'GAN' },
      { id: 'giade', name: 'Giade', code: 'GIA' },
      { id: 'itas-gadau', name: 'Itas/Gadau', code: 'ITA' },
      { id: 'jama-are', name: 'Jama\'are', code: 'JAM' },
      { id: 'katagum', name: 'Katagum', code: 'KAT' },
      { id: 'kirfi', name: 'Kirfi', code: 'KIR' },
      { id: 'misau', name: 'Misau', code: 'MIS' },
      { id: 'ningi', name: 'Ningi', code: 'NIN' },
      { id: 'shira', name: 'Shira', code: 'SHI' },
      { id: 'tafawa-balewa', name: 'Tafawa Balewa', code: 'TAF' },
      { id: 'toro', name: 'Toro', code: 'TOR' },
      { id: 'warji', name: 'Warji', code: 'WAR' },
      { id: 'zaki', name: 'Zaki', code: 'ZAK' }
    ]
  },
  {
    id: 'bayelsa',
    name: 'Bayelsa',
    code: 'BY',
    localGovernments: [
      { id: 'brass', name: 'Brass', code: 'BRA' },
      { id: 'ekeremor', name: 'Ekeremor', code: 'EKE' },
      { id: 'kolokuma-opokuma', name: 'Kolokuma/Opokuma', code: 'KOL' },
      { id: 'nembe', name: 'Nembe', code: 'NEM' },
      { id: 'ogbia', name: 'Ogbia', code: 'OGB' },
      { id: 'sagbama', name: 'Sagbama', code: 'SAG' },
      { id: 'southern-ijaw', name: 'Southern Ijaw', code: 'SIJ' },
      { id: 'yenagoa', name: 'Yenagoa', code: 'YEN' }
    ]
  },
  {
    id: 'benue',
    name: 'Benue',
    code: 'BE',
    localGovernments: [
      { id: 'ado', name: 'Ado', code: 'ADO' },
      { id: 'agatu', name: 'Agatu', code: 'AGA' },
      { id: 'apa', name: 'Apa', code: 'APA' },
      { id: 'buruku', name: 'Buruku', code: 'BUR' },
      { id: 'gboko', name: 'Gboko', code: 'GBO' },
      { id: 'guma', name: 'Guma', code: 'GUM' },
      { id: 'gwer-east', name: 'Gwer East', code: 'GWE' },
      { id: 'gwer-west', name: 'Gwer West', code: 'GWW' },
      { id: 'katsina-ala', name: 'Katsina-Ala', code: 'KAT' },
      { id: 'konshisha', name: 'Konshisha', code: 'KON' },
      { id: 'kwande', name: 'Kwande', code: 'KWA' },
      { id: 'logo', name: 'Logo', code: 'LOG' },
      { id: 'makurdi', name: 'Makurdi', code: 'MAK' },
      { id: 'obi', name: 'Obi', code: 'OBI' },
      { id: 'ogbadibo', name: 'Ogbadibo', code: 'OGB' },
      { id: 'ohimini', name: 'Ohimini', code: 'OHI' },
      { id: 'oju', name: 'Oju', code: 'OJU' },
      { id: 'okpokwu', name: 'Okpokwu', code: 'OKP' },
      { id: 'otukpo', name: 'Otukpo', code: 'OTU' },
      { id: 'tarka', name: 'Tarka', code: 'TAR' },
      { id: 'ukum', name: 'Ukum', code: 'UKU' },
      { id: 'ushongo', name: 'Ushongo', code: 'USH' },
      { id: 'vandeikya', name: 'Vandeikya', code: 'VAN' }
    ]
  },
  {
    id: 'borno',
    name: 'Borno',
    code: 'BO',
    localGovernments: [
      { id: 'abadam', name: 'Abadam', code: 'ABA' },
      { id: 'askira-uba', name: 'Askira/Uba', code: 'ASK' },
      { id: 'bama', name: 'Bama', code: 'BAM' },
      { id: 'bayo', name: 'Bayo', code: 'BAY' },
      { id: 'biu', name: 'Biu', code: 'BIU' },
      { id: 'chibok', name: 'Chibok', code: 'CHI' },
      { id: 'damboa', name: 'Damboa', code: 'DAM' },
      { id: 'dikwa', name: 'Dikwa', code: 'DIK' },
      { id: 'gubio', name: 'Gubio', code: 'GUB' },
      { id: 'guzamala', name: 'Guzamala', code: 'GUZ' },
      { id: 'gwoza', name: 'Gwoza', code: 'GWO' },
      { id: 'hawul', name: 'Hawul', code: 'HAW' },
      { id: 'jere', name: 'Jere', code: 'JER' },
      { id: 'kaga', name: 'Kaga', code: 'KAG' },
      { id: 'kala-balge', name: 'Kala/Balge', code: 'KAL' },
      { id: 'konduga', name: 'Konduga', code: 'KON' },
      { id: 'kukawa', name: 'Kukawa', code: 'KUK' },
      { id: 'kwaya-kusar', name: 'Kwaya Kusar', code: 'KWA' },
      { id: 'mafa', name: 'Mafa', code: 'MAF' },
      { id: 'magumeri', name: 'Magumeri', code: 'MAG' },
      { id: 'maiduguri', name: 'Maiduguri', code: 'MAI' },
      { id: 'marte', name: 'Marte', code: 'MAR' },
      { id: 'mobbar', name: 'Mobbar', code: 'MOB' },
      { id: 'monguno', name: 'Monguno', code: 'MON' },
      { id: 'ngala', name: 'Ngala', code: 'NGA' },
      { id: 'nganzai', name: 'Nganzai', code: 'NGZ' },
      { id: 'shani', name: 'Shani', code: 'SHA' }
    ]
  },
  {
    id: 'cross-river',
    name: 'Cross River',
    code: 'CR',
    localGovernments: [
      { id: 'abi', name: 'Abi', code: 'ABI' },
      { id: 'akamkpa', name: 'Akamkpa', code: 'AKA' },
      { id: 'akpabuyo', name: 'Akpabuyo', code: 'AKP' },
      { id: 'bakassi', name: 'Bakassi', code: 'BAK' },
      { id: 'bekwarra', name: 'Bekwarra', code: 'BEK' },
      { id: 'biase', name: 'Biase', code: 'BIA' },
      { id: 'boki', name: 'Boki', code: 'BOK' },
      { id: 'calabar-municipal', name: 'Calabar Municipal', code: 'CAM' },
      { id: 'calabar-south', name: 'Calabar South', code: 'CAS' },
      { id: 'etung', name: 'Etung', code: 'ETU' },
      { id: 'ikom', name: 'Ikom', code: 'IKO' },
      { id: 'obanliku', name: 'Obanliku', code: 'OBA' },
      { id: 'obubra', name: 'Obubra', code: 'OBU' },
      { id: 'obudu', name: 'Obudu', code: 'OBD' },
      { id: 'odukpani', name: 'Odukpani', code: 'ODU' },
      { id: 'ogoja', name: 'Ogoja', code: 'OGO' },
      { id: 'yakuur', name: 'Yakuur', code: 'YAK' },
      { id: 'yala', name: 'Yala', code: 'YAL' }
    ]
  },
  {
    id: 'delta',
    name: 'Delta',
    code: 'DE',
    localGovernments: [
      { id: 'aniocha-north', name: 'Aniocha North', code: 'ANN' },
      { id: 'aniocha-south', name: 'Aniocha South', code: 'ANS' },
      { id: 'bomadi', name: 'Bomadi', code: 'BOM' },
      { id: 'burutu', name: 'Burutu', code: 'BUR' },
      { id: 'ethiope-east', name: 'Ethiope East', code: 'ETE' },
      { id: 'ethiope-west', name: 'Ethiope West', code: 'ETW' },
      { id: 'ika-north-east', name: 'Ika North East', code: 'IKN' },
      { id: 'ika-south', name: 'Ika South', code: 'IKS' },
      { id: 'isoko-north', name: 'Isoko North', code: 'ISN' },
      { id: 'isoko-south', name: 'Isoko South', code: 'ISS' },
      { id: 'ndokwa-east', name: 'Ndokwa East', code: 'NDE' },
      { id: 'ndokwa-west', name: 'Ndokwa West', code: 'NDW' },
      { id: 'okpe', name: 'Okpe', code: 'OKP' },
      { id: 'oshimili-north', name: 'Oshimili North', code: 'OSN' },
      { id: 'oshimili-south', name: 'Oshimili South', code: 'OSS' },
      { id: 'patani', name: 'Patani', code: 'PAT' },
      { id: 'sapele', name: 'Sapele', code: 'SAP' },
      { id: 'udu', name: 'Udu', code: 'UDU' },
      { id: 'ughelli-north', name: 'Ughelli North', code: 'UGN' },
      { id: 'ughelli-south', name: 'Ughelli South', code: 'UGS' },
      { id: 'ukwuani', name: 'Ukwuani', code: 'UKW' },
      { id: 'uvwie', name: 'Uvwie', code: 'UVW' },
      { id: 'warri-north', name: 'Warri North', code: 'WAN' },
      { id: 'warri-south', name: 'Warri South', code: 'WAS' },
      { id: 'warri-south-west', name: 'Warri South West', code: 'WSW' }
    ]
  },
  {
    id: 'ebonyi',
    name: 'Ebonyi',
    code: 'EB',
    localGovernments: [
      { id: 'abakaliki', name: 'Abakaliki', code: 'ABA' },
      { id: 'afikpo-north', name: 'Afikpo North', code: 'AFN' },
      { id: 'afikpo-south', name: 'Afikpo South', code: 'AFS' },
      { id: 'ebonyi', name: 'Ebonyi', code: 'EBO' },
      { id: 'ezza-north', name: 'Ezza North', code: 'EZN' },
      { id: 'ezza-south', name: 'Ezza South', code: 'EZS' },
      { id: 'ikwo', name: 'Ikwo', code: 'IKW' },
      { id: 'ishielu', name: 'Ishielu', code: 'ISH' },
      { id: 'ivo', name: 'Ivo', code: 'IVO' },
      { id: 'izzi', name: 'Izzi', code: 'IZZ' },
      { id: 'ohaozara', name: 'Ohaozara', code: 'OHA' },
      { id: 'ohaukwu', name: 'Ohaukwu', code: 'OHU' },
      { id: 'onicha', name: 'Onicha', code: 'ONI' }
    ]
  },
  {
    id: 'edo',
    name: 'Edo',
    code: 'ED',
    localGovernments: [
      { id: 'akoko-edo', name: 'Akoko-Edo', code: 'AKO' },
      { id: 'egor', name: 'Egor', code: 'EGO' },
      { id: 'esan-central', name: 'Esan Central', code: 'ESC' },
      { id: 'esan-north-east', name: 'Esan North-East', code: 'ESN' },
      { id: 'esan-south-east', name: 'Esan South-East', code: 'ESS' },
      { id: 'esan-west', name: 'Esan West', code: 'ESW' },
      { id: 'etsako-central', name: 'Etsako Central', code: 'ETC' },
      { id: 'etsako-east', name: 'Etsako East', code: 'ETE' },
      { id: 'etsako-west', name: 'Etsako West', code: 'ETW' },
      { id: 'igueben', name: 'Igueben', code: 'IGU' },
      { id: 'ikpoba-okha', name: 'Ikpoba Okha', code: 'IKP' },
      { id: 'oredo', name: 'Oredo', code: 'ORE' },
      { id: 'orhionmwon', name: 'Orhionmwon', code: 'ORH' },
      { id: 'ovia-north-east', name: 'Ovia North-East', code: 'OVN' },
      { id: 'ovia-south-west', name: 'Ovia South-West', code: 'OVS' },
      { id: 'owan-east', name: 'Owan East', code: 'OWE' },
      { id: 'owan-west', name: 'Owan West', code: 'OWW' },
      { id: 'uhunmwonde', name: 'Uhunmwonde', code: 'UHU' }
    ]
  },
  {
    id: 'ekiti',
    name: 'Ekiti',
    code: 'EK',
    localGovernments: [
      { id: 'ado-ekiti', name: 'Ado Ekiti', code: 'ADO' },
      { id: 'efon', name: 'Efon', code: 'EFO' },
      { id: 'ekiti-east', name: 'Ekiti East', code: 'EKE' },
      { id: 'ekiti-south-west', name: 'Ekiti South-West', code: 'EKS' },
      { id: 'ekiti-west', name: 'Ekiti West', code: 'EKW' },
      { id: 'emure', name: 'Emure', code: 'EMU' },
      { id: 'gbonyin', name: 'Gbonyin', code: 'GBO' },
      { id: 'ido-osi', name: 'Ido Osi', code: 'IDO' },
      { id: 'ijero', name: 'Ijero', code: 'IJE' },
      { id: 'ikere', name: 'Ikere', code: 'IKE' },
      { id: 'ikole', name: 'Ikole', code: 'IKO' },
      { id: 'ilejemeje', name: 'Ilejemeje', code: 'ILE' },
      { id: 'irepodun-ifelodun', name: 'Irepodun/Ifelodun', code: 'IRE' },
      { id: 'ise-orun', name: 'Ise/Orun', code: 'ISE' },
      { id: 'moba', name: 'Moba', code: 'MOB' },
      { id: 'oye', name: 'Oye', code: 'OYE' }
    ]
  },
  {
    id: 'enugu',
    name: 'Enugu',
    code: 'EN',
    localGovernments: [
      { id: 'aninri', name: 'Aninri', code: 'ANI' },
      { id: 'awgu', name: 'Awgu', code: 'AWG' },
      { id: 'enugu-east', name: 'Enugu East', code: 'ENE' },
      { id: 'enugu-north', name: 'Enugu North', code: 'ENN' },
      { id: 'enugu-south', name: 'Enugu South', code: 'ENS' },
      { id: 'ezeagu', name: 'Ezeagu', code: 'EZE' },
      { id: 'igbo-etiti', name: 'Igbo Etiti', code: 'IGE' },
      { id: 'igbo-eze-north', name: 'Igbo Eze North', code: 'IGN' },
      { id: 'igbo-eze-south', name: 'Igbo Eze South', code: 'IGS' },
      { id: 'isi-uzo', name: 'Isi Uzo', code: 'ISI' },
      { id: 'nkanu-east', name: 'Nkanu East', code: 'NKE' },
      { id: 'nkanu-west', name: 'Nkanu West', code: 'NKW' },
      { id: 'nsukka', name: 'Nsukka', code: 'NSU' },
      { id: 'oji-river', name: 'Oji River', code: 'OJI' },
      { id: 'udenu', name: 'Udenu', code: 'UDE' },
      { id: 'udi', name: 'Udi', code: 'UDI' },
      { id: 'uzo-uwani', name: 'Uzo Uwani', code: 'UZO' }
    ]
  },
  {
    id: 'fct',
    name: 'Federal Capital Territory',
    code: 'FC',
    localGovernments: [
      { id: 'abaji', name: 'Abaji', code: 'ABJ' },
      { id: 'bwari', name: 'Bwari', code: 'BWA' },
      { id: 'gwagwalada', name: 'Gwagwalada', code: 'GWA' },
      { id: 'kuje', name: 'Kuje', code: 'KUJ' },
      { id: 'kwali', name: 'Kwali', code: 'KWA' },
      { id: 'municipal-area-council', name: 'Municipal Area Council', code: 'MAC' }
    ]
  },
  {
    id: 'gombe',
    name: 'Gombe',
    code: 'GO',
    localGovernments: [
      { id: 'akko', name: 'Akko', code: 'AKK' },
      { id: 'balanga', name: 'Balanga', code: 'BAL' },
      { id: 'billiri', name: 'Billiri', code: 'BIL' },
      { id: 'dukku', name: 'Dukku', code: 'DUK' },
      { id: 'funakaye', name: 'Funakaye', code: 'FUN' },
      { id: 'gombe', name: 'Gombe', code: 'GOM' },
      { id: 'kaltungo', name: 'Kaltungo', code: 'KAL' },
      { id: 'kwami', name: 'Kwami', code: 'KWA' },
      { id: 'nafada', name: 'Nafada', code: 'NAF' },
      { id: 'shongom', name: 'Shongom', code: 'SHO' },
      { id: 'yamaltu-deba', name: 'Yamaltu/Deba', code: 'YAM' }
    ]
  },
  {
    id: 'imo',
    name: 'Imo',
    code: 'IM',
    localGovernments: [
      { id: 'aboh-mbaise', name: 'Aboh Mbaise', code: 'ABO' },
      { id: 'ahiazu-mbaise', name: 'Ahiazu Mbaise', code: 'AHI' },
      { id: 'ehime-mbano', name: 'Ehime Mbano', code: 'EHI' },
      { id: 'ezinihitte', name: 'Ezinihitte', code: 'EZI' },
      { id: 'ideato-north', name: 'Ideato North', code: 'IDN' },
      { id: 'ideato-south', name: 'Ideato South', code: 'IDS' },
      { id: 'ihitte-uboma', name: 'Ihitte/Uboma', code: 'IHI' },
      { id: 'ikeduru', name: 'Ikeduru', code: 'IKE' },
      { id: 'isiala-mbano', name: 'Isiala Mbano', code: 'ISI' },
      { id: 'isu', name: 'Isu', code: 'ISU' },
      { id: 'mbaitoli', name: 'Mbaitoli', code: 'MBA' },
      { id: 'ngor-okpala', name: 'Ngor Okpala', code: 'NGO' },
      { id: 'njaba', name: 'Njaba', code: 'NJA' },
      { id: 'nkwerre', name: 'Nkwerre', code: 'NKW' },
      { id: 'nwangele', name: 'Nwangele', code: 'NWA' },
      { id: 'obowo', name: 'Obowo', code: 'OBO' },
      { id: 'oguta', name: 'Oguta', code: 'OGU' },
      { id: 'ohaji-egbema', name: 'Ohaji/Egbema', code: 'OHA' },
      { id: 'okigwe', name: 'Okigwe', code: 'OKI' },
      { id: 'orlu', name: 'Orlu', code: 'ORL' },
      { id: 'orsu', name: 'Orsu', code: 'ORS' },
      { id: 'oru-east', name: 'Oru East', code: 'ORE' },
      { id: 'oru-west', name: 'Oru West', code: 'ORW' },
      { id: 'owerri-municipal', name: 'Owerri Municipal', code: 'OWM' },
      { id: 'owerri-north', name: 'Owerri North', code: 'OWN' },
      { id: 'owerri-west', name: 'Owerri West', code: 'OWW' },
      { id: 'unuimo', name: 'Unuimo', code: 'UNU' }
    ]
  },
  {
    id: 'jigawa',
    name: 'Jigawa',
    code: 'JI',
    localGovernments: [
      { id: 'auyo', name: 'Auyo', code: 'AUY' },
      { id: 'babura', name: 'Babura', code: 'BAB' },
      { id: 'biriniwa', name: 'Biriniwa', code: 'BIR' },
      { id: 'birnin-kudu', name: 'Birnin Kudu', code: 'BIK' },
      { id: 'buji', name: 'Buji', code: 'BUJ' },
      { id: 'dutse', name: 'Dutse', code: 'DUT' },
      { id: 'gagarawa', name: 'Gagarawa', code: 'GAG' },
      { id: 'garki', name: 'Garki', code: 'GAR' },
      { id: 'gumel', name: 'Gumel', code: 'GUM' },
      { id: 'guri', name: 'Guri', code: 'GUR' },
      { id: 'gwaram', name: 'Gwaram', code: 'GWA' },
      { id: 'gwiwa', name: 'Gwiwa', code: 'GWI' },
      { id: 'hadejia', name: 'Hadejia', code: 'HAD' },
      { id: 'jahun', name: 'Jahun', code: 'JAH' },
      { id: 'kafin-hausa', name: 'Kafin Hausa', code: 'KAF' },
      { id: 'kazaure', name: 'Kazaure', code: 'KAZ' },
      { id: 'kiri-kasama', name: 'Kiri Kasama', code: 'KIR' },
      { id: 'kiyawa', name: 'Kiyawa', code: 'KIY' },
      { id: 'kaugama', name: 'Kaugama', code: 'KAU' },
      { id: 'maigatari', name: 'Maigatari', code: 'MAI' },
      { id: 'malam-madori', name: 'Malam Madori', code: 'MAL' },
      { id: 'miga', name: 'Miga', code: 'MIG' },
      { id: 'ringim', name: 'Ringim', code: 'RIN' },
      { id: 'roni', name: 'Roni', code: 'RON' },
      { id: 'sule-tankarkar', name: 'Sule Tankarkar', code: 'SUL' },
      { id: 'taura', name: 'Taura', code: 'TAU' },
      { id: 'yankwashi', name: 'Yankwashi', code: 'YAN' }
    ]
  },
  {
    id: 'kaduna',
    name: 'Kaduna',
    code: 'KD',
    localGovernments: [
      { id: 'birnin-gwari', name: 'Birnin Gwari', code: 'BIG' },
      { id: 'chikun', name: 'Chikun', code: 'CHI' },
      { id: 'giwa', name: 'Giwa', code: 'GIW' },
      { id: 'igabi', name: 'Igabi', code: 'IGA' },
      { id: 'ikara', name: 'Ikara', code: 'IKA' },
      { id: 'jaba', name: 'Jaba', code: 'JAB' },
      { id: 'jema-a', name: 'Jema\'a', code: 'JEM' },
      { id: 'kachia', name: 'Kachia', code: 'KAC' },
      { id: 'kaduna-north', name: 'Kaduna North', code: 'KAN' },
      { id: 'kaduna-south', name: 'Kaduna South', code: 'KAS' },
      { id: 'kagarko', name: 'Kagarko', code: 'KAG' },
      { id: 'kajuru', name: 'Kajuru', code: 'KAJ' },
      { id: 'kaura', name: 'Kaura', code: 'KAU' },
      { id: 'kauru', name: 'Kauru', code: 'KUR' },
      { id: 'kubau', name: 'Kubau', code: 'KUB' },
      { id: 'kudan', name: 'Kudan', code: 'KUD' },
      { id: 'lere', name: 'Lere', code: 'LER' },
      { id: 'makarfi', name: 'Makarfi', code: 'MAK' },
      { id: 'sabon-gari', name: 'Sabon Gari', code: 'SAB' },
      { id: 'sanga', name: 'Sanga', code: 'SAN' },
      { id: 'soba', name: 'Soba', code: 'SOB' },
      { id: 'zangon-kataf', name: 'Zangon Kataf', code: 'ZAN' },
      { id: 'zaria', name: 'Zaria', code: 'ZAR' }
    ]
  },
  {
    id: 'kano',
    name: 'Kano',
    code: 'KN',
    localGovernments: [
      { id: 'ajingi', name: 'Ajingi', code: 'AJI' },
      { id: 'albasu', name: 'Albasu', code: 'ALB' },
      { id: 'bagwai', name: 'Bagwai', code: 'BAG' },
      { id: 'bebeji', name: 'Bebeji', code: 'BEB' },
      { id: 'bichi', name: 'Bichi', code: 'BIC' },
      { id: 'bunkure', name: 'Bunkure', code: 'BUN' },
      { id: 'dala', name: 'Dala', code: 'DAL' },
      { id: 'dambatta', name: 'Dambatta', code: 'DAM' },
      { id: 'dawkin-kudu', name: 'Dawkin Kudu', code: 'DAW' },
      { id: 'dawkin-tofa', name: 'Dawkin Tofa', code: 'DAT' },
      { id: 'doguwa', name: 'Doguwa', code: 'DOG' },
      { id: 'fagge', name: 'Fagge', code: 'FAG' },
      { id: 'gabasawa', name: 'Gabasawa', code: 'GAB' },
      { id: 'garko', name: 'Garko', code: 'GAR' },
      { id: 'garun-mallam', name: 'Garun Mallam', code: 'GAM' },
      { id: 'gaya', name: 'Gaya', code: 'GAY' },
      { id: 'gezawa', name: 'Gezawa', code: 'GEZ' },
      { id: 'gwale', name: 'Gwale', code: 'GWA' },
      { id: 'gwarzo', name: 'Gwarzo', code: 'GWZ' },
      { id: 'kabo', name: 'Kabo', code: 'KAB' },
      { id: 'kano-municipal', name: 'Kano Municipal', code: 'KAN' },
      { id: 'karaye', name: 'Karaye', code: 'KAR' },
      { id: 'kibiya', name: 'Kibiya', code: 'KIB' },
      { id: 'kiru', name: 'Kiru', code: 'KIR' },
      { id: 'kumbotso', name: 'Kumbotso', code: 'KUM' },
      { id: 'kunchi', name: 'Kunchi', code: 'KUN' },
      { id: 'kura', name: 'Kura', code: 'KUR' },
      { id: 'madobi', name: 'Madobi', code: 'MAD' },
      { id: 'makoda', name: 'Makoda', code: 'MAK' },
      { id: 'minjibir', name: 'Minjibir', code: 'MIN' },
      { id: 'nasarawa', name: 'Nasarawa', code: 'NAS' },
      { id: 'rano', name: 'Rano', code: 'RAN' },
      { id: 'rimin-gado', name: 'Rimin Gado', code: 'RIM' },
      { id: 'rogo', name: 'Rogo', code: 'ROG' },
      { id: 'shanono', name: 'Shanono', code: 'SHA' },
      { id: 'sumaila', name: 'Sumaila', code: 'SUM' },
      { id: 'takai', name: 'Takai', code: 'TAK' },
      { id: 'tarauni', name: 'Tarauni', code: 'TAR' },
      { id: 'tofa', name: 'Tofa', code: 'TOF' },
      { id: 'tsanyawa', name: 'Tsanyawa', code: 'TSA' },
      { id: 'tudun-wada', name: 'Tudun Wada', code: 'TUD' },
      { id: 'ungogo', name: 'Ungogo', code: 'UNG' },
      { id: 'warawa', name: 'Warawa', code: 'WAR' },
      { id: 'wudil', name: 'Wudil', code: 'WUD' }
    ]
  },
  {
    id: 'katsina',
    name: 'Katsina',
    code: 'KT',
    localGovernments: [
      { id: 'bakori', name: 'Bakori', code: 'BAK' },
      { id: 'batagarawa', name: 'Batagarawa', code: 'BAT' },
      { id: 'batsari', name: 'Batsari', code: 'BTS' },
      { id: 'baure', name: 'Baure', code: 'BAU' },
      { id: 'bindawa', name: 'Bindawa', code: 'BIN' },
      { id: 'charanchi', name: 'Charanchi', code: 'CHA' },
      { id: 'dandume', name: 'Dandume', code: 'DAN' },
      { id: 'danja', name: 'Danja', code: 'DNJ' },
      { id: 'dan-musa', name: 'Dan Musa', code: 'DAM' },
      { id: 'daura', name: 'Daura', code: 'DAU' },
      { id: 'dutsi', name: 'Dutsi', code: 'DUT' },
      { id: 'dutsin-ma', name: 'Dutsin Ma', code: 'DMA' },
      { id: 'faskari', name: 'Faskari', code: 'FAS' },
      { id: 'funtua', name: 'Funtua', code: 'FUN' },
      { id: 'ingawa', name: 'Ingawa', code: 'ING' },
      { id: 'jibia', name: 'Jibia', code: 'JIB' },
      { id: 'kafur', name: 'Kafur', code: 'KAF' },
      { id: 'kaita', name: 'Kaita', code: 'KAI' },
      { id: 'kankara', name: 'Kankara', code: 'KAN' },
      { id: 'kankia', name: 'Kankia', code: 'KNK' },
      { id: 'katsina', name: 'Katsina', code: 'KAT' },
      { id: 'kurfi', name: 'Kurfi', code: 'KUR' },
      { id: 'kusada', name: 'Kusada', code: 'KUS' },
      { id: 'mai-adua', name: 'Mai\'Adua', code: 'MAI' },
      { id: 'malumfashi', name: 'Malumfashi', code: 'MAL' },
      { id: 'mani', name: 'Mani', code: 'MAN' },
      { id: 'mashi', name: 'Mashi', code: 'MAS' },
      { id: 'matazu', name: 'Matazu', code: 'MAT' },
      { id: 'musawa', name: 'Musawa', code: 'MUS' },
      { id: 'rimi', name: 'Rimi', code: 'RIM' },
      { id: 'sabuwa', name: 'Sabuwa', code: 'SAB' },
      { id: 'safana', name: 'Safana', code: 'SAF' },
      { id: 'sandamu', name: 'Sandamu', code: 'SAN' },
      { id: 'zango', name: 'Zango', code: 'ZAN' }
    ]
  },
  {
    id: 'kebbi',
    name: 'Kebbi',
    code: 'KE',
    localGovernments: [
      { id: 'aleiro', name: 'Aleiro', code: 'ALE' },
      { id: 'arewa-dandi', name: 'Arewa Dandi', code: 'ARE' },
      { id: 'argungu', name: 'Argungu', code: 'ARG' },
      { id: 'augie', name: 'Augie', code: 'AUG' },
      { id: 'bagudo', name: 'Bagudo', code: 'BAG' },
      { id: 'birnin-kebbi', name: 'Birnin Kebbi', code: 'BIR' },
      { id: 'bunza', name: 'Bunza', code: 'BUN' },
      { id: 'dandi', name: 'Dandi', code: 'DAN' },
      { id: 'fakai', name: 'Fakai', code: 'FAK' },
      { id: 'gwandu', name: 'Gwandu', code: 'GWA' },
      { id: 'jega', name: 'Jega', code: 'JEG' },
      { id: 'kalgo', name: 'Kalgo', code: 'KAL' },
      { id: 'koko-besse', name: 'Koko/Besse', code: 'KOK' },
      { id: 'maiyama', name: 'Maiyama', code: 'MAI' },
      { id: 'ngaski', name: 'Ngaski', code: 'NGA' },
      { id: 'sakaba', name: 'Sakaba', code: 'SAK' },
      { id: 'shanga', name: 'Shanga', code: 'SHA' },
      { id: 'suru', name: 'Suru', code: 'SUR' },
      { id: 'wasagu-danko', name: 'Wasagu/Danko', code: 'WAS' },
      { id: 'yauri', name: 'Yauri', code: 'YAU' },
      { id: 'zuru', name: 'Zuru', code: 'ZUR' }
    ]
  },
  {
    id: 'kogi',
    name: 'Kogi',
    code: 'KO',
    localGovernments: [
      { id: 'adavi', name: 'Adavi', code: 'ADA' },
      { id: 'ajaokuta', name: 'Ajaokuta', code: 'AJA' },
      { id: 'ankpa', name: 'Ankpa', code: 'ANK' },
      { id: 'bassa', name: 'Bassa', code: 'BAS' },
      { id: 'dekina', name: 'Dekina', code: 'DEK' },
      { id: 'ibaji', name: 'Ibaji', code: 'IBA' },
      { id: 'idah', name: 'Idah', code: 'IDA' },
      { id: 'igalamela-odolu', name: 'Igalamela Odolu', code: 'IGA' },
      { id: 'ijumu', name: 'Ijumu', code: 'IJU' },
      { id: 'kabba-bunu', name: 'Kabba/Bunu', code: 'KAB' },
      { id: 'kogi', name: 'Kogi', code: 'KOG' },
      { id: 'lokoja', name: 'Lokoja', code: 'LOK' },
      { id: 'mopa-muro', name: 'Mopa Muro', code: 'MOP' },
      { id: 'ofu', name: 'Ofu', code: 'OFU' },
      { id: 'ogori-magongo', name: 'Ogori/Magongo', code: 'OGO' },
      { id: 'okehi', name: 'Okehi', code: 'OKE' },
      { id: 'okene', name: 'Okene', code: 'OKN' },
      { id: 'olamaboro', name: 'Olamaboro', code: 'OLA' },
      { id: 'omala', name: 'Omala', code: 'OMA' },
      { id: 'yagba-east', name: 'Yagba East', code: 'YAE' },
      { id: 'yagba-west', name: 'Yagba West', code: 'YAW' }
    ]
  },
  {
    id: 'kwara',
    name: 'Kwara',
    code: 'KW',
    localGovernments: [
      { id: 'asa', name: 'Asa', code: 'ASA' },
      { id: 'baruten', name: 'Baruten', code: 'BAR' },
      { id: 'edu', name: 'Edu', code: 'EDU' },
      { id: 'ekiti', name: 'Ekiti', code: 'EKI' },
      { id: 'ifelodun', name: 'Ifelodun', code: 'IFE' },
      { id: 'ilorin-east', name: 'Ilorin East', code: 'ILE' },
      { id: 'ilorin-south', name: 'Ilorin South', code: 'ILS' },
      { id: 'ilorin-west', name: 'Ilorin West', code: 'ILW' },
      { id: 'irepodun', name: 'Irepodun', code: 'IRE' },
      { id: 'isin', name: 'Isin', code: 'ISI' },
      { id: 'kaiama', name: 'Kaiama', code: 'KAI' },
      { id: 'moro', name: 'Moro', code: 'MOR' },
      { id: 'offa', name: 'Offa', code: 'OFF' },
      { id: 'oke-ero', name: 'Oke Ero', code: 'OKE' },
      { id: 'oyun', name: 'Oyun', code: 'OYU' },
      { id: 'pategi', name: 'Pategi', code: 'PAT' }
    ]
  },
  {
    id: 'lagos',
    name: 'Lagos',
    code: 'LA',
    localGovernments: [
      { id: 'agege', name: 'Agege', code: 'AGE' },
      { id: 'ajeromi-ifelodun', name: 'Ajeromi-Ifelodun', code: 'AJE' },
      { id: 'alimosho', name: 'Alimosho', code: 'ALI' },
      { id: 'amuwo-odofin', name: 'Amuwo-Odofin', code: 'AMU' },
      { id: 'apapa', name: 'Apapa', code: 'APA' },
      { id: 'badagry', name: 'Badagry', code: 'BAD' },
      { id: 'epe', name: 'Epe', code: 'EPE' },
      { id: 'eti-osa', name: 'Eti Osa', code: 'ETI' },
      { id: 'ibeju-lekki', name: 'Ibeju-Lekki', code: 'IBE' },
      { id: 'ifako-ijaiye', name: 'Ifako-Ijaiye', code: 'IFA' },
      { id: 'ikeja', name: 'Ikeja', code: 'IKE' },
      { id: 'ikorodu', name: 'Ikorodu', code: 'IKO' },
      { id: 'kosofe', name: 'Kosofe', code: 'KOS' },
      { id: 'lagos-island', name: 'Lagos Island', code: 'LAI' },
      { id: 'lagos-mainland', name: 'Lagos Mainland', code: 'LAM' },
      { id: 'mushin', name: 'Mushin', code: 'MUS' },
      { id: 'ojo', name: 'Ojo', code: 'OJO' },
      { id: 'oshodi-isolo', name: 'Oshodi-Isolo', code: 'OSH' },
      { id: 'shomolu', name: 'Shomolu', code: 'SHO' },
      { id: 'surulere', name: 'Surulere', code: 'SUR' }
    ]
  },
  {
    id: 'nasarawa',
    name: 'Nasarawa',
    code: 'NA',
    localGovernments: [
      { id: 'akwanga', name: 'Akwanga', code: 'AKW' },
      { id: 'awe', name: 'Awe', code: 'AWE' },
      { id: 'doma', name: 'Doma', code: 'DOM' },
      { id: 'karu', name: 'Karu', code: 'KAR' },
      { id: 'keana', name: 'Keana', code: 'KEA' },
      { id: 'keffi', name: 'Keffi', code: 'KEF' },
      { id: 'kokona', name: 'Kokona', code: 'KOK' },
      { id: 'lafia', name: 'Lafia', code: 'LAF' },
      { id: 'nasarawa', name: 'Nasarawa', code: 'NAS' },
      { id: 'nasarawa-egon', name: 'Nasarawa Egon', code: 'NAE' },
      { id: 'obi', name: 'Obi', code: 'OBI' },
      { id: 'toto', name: 'Toto', code: 'TOT' },
      { id: 'wamba', name: 'Wamba', code: 'WAM' }
    ]
  },
  {
    id: 'niger',
    name: 'Niger',
    code: 'NI',
    localGovernments: [
      { id: 'agaie', name: 'Agaie', code: 'AGA' },
      { id: 'agwara', name: 'Agwara', code: 'AGW' },
      { id: 'bida', name: 'Bida', code: 'BID' },
      { id: 'borgu', name: 'Borgu', code: 'BOR' },
      { id: 'bosso', name: 'Bosso', code: 'BOS' },
      { id: 'chanchaga', name: 'Chanchaga', code: 'CHA' },
      { id: 'edati', name: 'Edati', code: 'EDA' },
      { id: 'gbako', name: 'Gbako', code: 'GBA' },
      { id: 'gurara', name: 'Gurara', code: 'GUR' },
      { id: 'katcha', name: 'Katcha', code: 'KAT' },
      { id: 'kontagora', name: 'Kontagora', code: 'KON' },
      { id: 'lapai', name: 'Lapai', code: 'LAP' },
      { id: 'lavun', name: 'Lavun', code: 'LAV' },
      { id: 'magama', name: 'Magama', code: 'MAG' },
      { id: 'mariga', name: 'Mariga', code: 'MAR' },
      { id: 'mashegu', name: 'Mashegu', code: 'MAS' },
      { id: 'mokwa', name: 'Mokwa', code: 'MOK' },
      { id: 'moya', name: 'Moya', code: 'MOY' },
      { id: 'paikoro', name: 'Paikoro', code: 'PAI' },
      { id: 'rafi', name: 'Rafi', code: 'RAF' },
      { id: 'rijau', name: 'Rijau', code: 'RIJ' },
      { id: 'shiroro', name: 'Shiroro', code: 'SHI' },
      { id: 'suleja', name: 'Suleja', code: 'SUL' },
      { id: 'tafa', name: 'Tafa', code: 'TAF' },
      { id: 'wushishi', name: 'Wushishi', code: 'WUS' }
    ]
  },
  {
    id: 'ogun',
    name: 'Ogun',
    code: 'OG',
    localGovernments: [
      { id: 'abeokuta-north', name: 'Abeokuta North', code: 'ABN' },
      { id: 'abeokuta-south', name: 'Abeokuta South', code: 'ABS' },
      { id: 'ado-odo-ota', name: 'Ado-Odo/Ota', code: 'ADO' },
      { id: 'egbado-north', name: 'Egbado North', code: 'EGN' },
      { id: 'egbado-south', name: 'Egbado South', code: 'EGS' },
      { id: 'ewekoro', name: 'Ewekoro', code: 'EWE' },
      { id: 'ifo', name: 'Ifo', code: 'IFO' },
      { id: 'ijebu-east', name: 'Ijebu East', code: 'IJE' },
      { id: 'ijebu-north', name: 'Ijebu North', code: 'IJN' },
      { id: 'ijebu-north-east', name: 'Ijebu North East', code: 'IJNE' },
      { id: 'ijebu-ode', name: 'Ijebu Ode', code: 'IJO' },
      { id: 'ikenne', name: 'Ikenne', code: 'IKE' },
      { id: 'imeko-afon', name: 'Imeko Afon', code: 'IMA' },
      { id: 'ipokia', name: 'Ipokia', code: 'IPO' },
      { id: 'obafemi-owode', name: 'Obafemi Owode', code: 'OBA' },
      { id: 'odeda', name: 'Odeda', code: 'ODE' },
      { id: 'odogbolu', name: 'Odogbolu', code: 'ODO' },
      { id: 'ogun-waterside', name: 'Ogun Waterside', code: 'OGW' },
      { id: 'remo-north', name: 'Remo North', code: 'REN' },
      { id: 'shagamu', name: 'Shagamu', code: 'SHA' }
    ]
  },
  {
    id: 'ondo',
    name: 'Ondo',
    code: 'ON',
    localGovernments: [
      { id: 'akoko-north-east', name: 'Akoko North-East', code: 'AKNE' },
      { id: 'akoko-north-west', name: 'Akoko North-West', code: 'AKNW' },
      { id: 'akoko-south-east', name: 'Akoko South-East', code: 'AKSE' },
      { id: 'akoko-south-west', name: 'Akoko South-West', code: 'AKSW' },
      { id: 'akure-north', name: 'Akure North', code: 'AKN' },
      { id: 'akure-south', name: 'Akure South', code: 'AKS' },
      { id: 'ese-odo', name: 'Ese Odo', code: 'ESE' },
      { id: 'idanre', name: 'Idanre', code: 'IDA' },
      { id: 'ifedore', name: 'Ifedore', code: 'IFE' },
      { id: 'ilaje', name: 'Ilaje', code: 'ILA' },
      { id: 'ile-oluji-okeigbo', name: 'Ile Oluji/Okeigbo', code: 'ILO' },
      { id: 'irele', name: 'Irele', code: 'IRE' },
      { id: 'odigbo', name: 'Odigbo', code: 'ODI' },
      { id: 'okitipupa', name: 'Okitipupa', code: 'OKI' },
      { id: 'ondo-east', name: 'Ondo East', code: 'ONE' },
      { id: 'ondo-west', name: 'Ondo West', code: 'ONW' },
      { id: 'ose', name: 'Ose', code: 'OSE' },
      { id: 'owo', name: 'Owo', code: 'OWO' }
    ]
  },
  {
    id: 'osun',
    name: 'Osun',
    code: 'OS',
    localGovernments: [
      { id: 'atakunmosa-east', name: 'Atakunmosa East', code: 'ATE' },
      { id: 'atakunmosa-west', name: 'Atakunmosa West', code: 'ATW' },
      { id: 'aiyedaade', name: 'Aiyedaade', code: 'AIY' },
      { id: 'aiyedire', name: 'Aiyedire', code: 'AID' },
      { id: 'boluwaduro', name: 'Boluwaduro', code: 'BOL' },
      { id: 'boripe', name: 'Boripe', code: 'BOR' },
      { id: 'ede-north', name: 'Ede North', code: 'EDN' },
      { id: 'ede-south', name: 'Ede South', code: 'EDS' },
      { id: 'egbedore', name: 'Egbedore', code: 'EGB' },
      { id: 'ejigbo', name: 'Ejigbo', code: 'EJI' },
      { id: 'ife-central', name: 'Ife Central', code: 'IFC' },
      { id: 'ife-east', name: 'Ife East', code: 'IFE' },
      { id: 'ife-north', name: 'Ife North', code: 'IFN' },
      { id: 'ife-south', name: 'Ife South', code: 'IFS' },
      { id: 'ifedayo', name: 'Ifedayo', code: 'IFD' },
      { id: 'ifelodun', name: 'Ifelodun', code: 'IFL' },
      { id: 'ila', name: 'Ila', code: 'ILA' },
      { id: 'ilesa-east', name: 'Ilesa East', code: 'ILE' },
      { id: 'ilesa-west', name: 'Ilesa West', code: 'ILW' },
      { id: 'irepodun', name: 'Irepodun', code: 'IRE' },
      { id: 'irewole', name: 'Irewole', code: 'IRW' },
      { id: 'isokan', name: 'Isokan', code: 'ISO' },
      { id: 'iwo', name: 'Iwo', code: 'IWO' },
      { id: 'obokun', name: 'Obokun', code: 'OBO' },
      { id: 'odo-otin', name: 'Odo Otin', code: 'ODO' },
      { id: 'ola-oluwa', name: 'Ola Oluwa', code: 'OLA' },
      { id: 'olorunda', name: 'Olorunda', code: 'OLO' },
      { id: 'oriade', name: 'Oriade', code: 'ORI' },
      { id: 'orolu', name: 'Orolu', code: 'ORO' },
      { id: 'osogbo', name: 'Osogbo', code: 'OSO' }
    ]
  },
  {
    id: 'oyo',
    name: 'Oyo',
    code: 'OY',
    localGovernments: [
      { id: 'afijio', name: 'Afijio', code: 'AFI' },
      { id: 'akinyele', name: 'Akinyele', code: 'AKI' },
      { id: 'atiba', name: 'Atiba', code: 'ATI' },
      { id: 'atisbo', name: 'Atisbo', code: 'ATS' },
      { id: 'egbeda', name: 'Egbeda', code: 'EGB' },
      { id: 'ibadan-north', name: 'Ibadan North', code: 'IBN' },
      { id: 'ibadan-north-east', name: 'Ibadan North-East', code: 'IBNE' },
      { id: 'ibadan-north-west', name: 'Ibadan North-West', code: 'IBNW' },
      { id: 'ibadan-south-east', name: 'Ibadan South-East', code: 'IBSE' },
      { id: 'ibadan-south-west', name: 'Ibadan South-West', code: 'IBSW' },
      { id: 'ibarapa-central', name: 'Ibarapa Central', code: 'IBC' },
      { id: 'ibarapa-east', name: 'Ibarapa East', code: 'IBE' },
      { id: 'ibarapa-north', name: 'Ibarapa North', code: 'IBN' },
      { id: 'ido', name: 'Ido', code: 'IDO' },
      { id: 'irepo', name: 'Irepo', code: 'IRE' },
      { id: 'iseyin', name: 'Iseyin', code: 'ISE' },
      { id: 'itesiwaju', name: 'Itesiwaju', code: 'ITE' },
      { id: 'iwajowa', name: 'Iwajowa', code: 'IWA' },
      { id: 'kajola', name: 'Kajola', code: 'KAJ' },
      { id: 'lagelu', name: 'Lagelu', code: 'LAG' },
      { id: 'ogbomoso-north', name: 'Ogbomoso North', code: 'OGN' },
      { id: 'ogbomoso-south', name: 'Ogbomoso South', code: 'OGS' },
      { id: 'ogo-oluwa', name: 'Ogo Oluwa', code: 'OGO' },
      { id: 'olorunsogo', name: 'Olorunsogo', code: 'OLO' },
      { id: 'oluyole', name: 'Oluyole', code: 'OLU' },
      { id: 'ona-ara', name: 'Ona Ara', code: 'ONA' },
      { id: 'orelope', name: 'Orelope', code: 'ORE' },
      { id: 'ori-ire', name: 'Ori Ire', code: 'ORI' },
      { id: 'oyo-east', name: 'Oyo East', code: 'OYE' },
      { id: 'oyo-west', name: 'Oyo West', code: 'OYW' },
      { id: 'saki-east', name: 'Saki East', code: 'SAE' },
      { id: 'saki-west', name: 'Saki West', code: 'SAW' },
      { id: 'surulere', name: 'Surulere', code: 'SUR' }
    ]
  },
  {
    id: 'plateau',
    name: 'Plateau',
    code: 'PL',
    localGovernments: [
      { id: 'bokkos', name: 'Bokkos', code: 'BOK' },
      { id: 'barkin-ladi', name: 'Barkin Ladi', code: 'BAR' },
      { id: 'bassa', name: 'Bassa', code: 'BAS' },
      { id: 'jos-east', name: 'Jos East', code: 'JOE' },
      { id: 'jos-north', name: 'Jos North', code: 'JON' },
      { id: 'jos-south', name: 'Jos South', code: 'JOS' },
      { id: 'kanam', name: 'Kanam', code: 'KAN' },
      { id: 'kanke', name: 'Kanke', code: 'KAK' },
      { id: 'langtang-north', name: 'Langtang North', code: 'LAN' },
      { id: 'langtang-south', name: 'Langtang South', code: 'LAS' },
      { id: 'mangu', name: 'Mangu', code: 'MAN' },
      { id: 'mikang', name: 'Mikang', code: 'MIK' },
      { id: 'pankshin', name: 'Pankshin', code: 'PAN' },
      { id: 'qua-an-pan', name: 'Qua\'an Pan', code: 'QUA' },
      { id: 'riyom', name: 'Riyom', code: 'RIY' },
      { id: 'shendam', name: 'Shendam', code: 'SHE' },
      { id: 'wase', name: 'Wase', code: 'WAS' }
    ]
  },
  {
    id: 'rivers',
    name: 'Rivers',
    code: 'RI',
    localGovernments: [
      { id: 'abua-odual', name: 'Abua/Odual', code: 'ABO' },
      { id: 'ahoada-east', name: 'Ahoada East', code: 'AHE' },
      { id: 'ahoada-west', name: 'Ahoada West', code: 'AHW' },
      { id: 'akuku-toru', name: 'Akuku-Toru', code: 'AKU' },
      { id: 'andoni', name: 'Andoni', code: 'AND' },
      { id: 'asari-toru', name: 'Asari-Toru', code: 'ASA' },
      { id: 'bonny', name: 'Bonny', code: 'BON' },
      { id: 'degema', name: 'Degema', code: 'DEG' },
      { id: 'eleme', name: 'Eleme', code: 'ELE' },
      { id: 'emuoha', name: 'Emuoha', code: 'EMU' },
      { id: 'etche', name: 'Etche', code: 'ETC' },
      { id: 'gokana', name: 'Gokana', code: 'GOK' },
      { id: 'ikwerre', name: 'Ikwerre', code: 'IKW' },
      { id: 'khana', name: 'Khana', code: 'KHA' },
      { id: 'obio-akpor', name: 'Obio-Akpor', code: 'OBI' },
      { id: 'ogba-egbema-ndoni', name: 'Ogba/Egbema/Ndoni', code: 'OGE' },
      { id: 'ogu-bolo', name: 'Ogu/Bolo', code: 'OGU' },
      { id: 'okrika', name: 'Okrika', code: 'OKR' },
      { id: 'omuma', name: 'Omuma', code: 'OMU' },
      { id: 'opobo-nkoro', name: 'Opobo/Nkoro', code: 'OPO' },
      { id: 'oyigbo', name: 'Oyigbo', code: 'OYI' },
      { id: 'port-harcourt', name: 'Port Harcourt', code: 'POR' },
      { id: 'tai', name: 'Tai', code: 'TAI' }
    ]
  },
  {
    id: 'sokoto',
    name: 'Sokoto',
    code: 'SO',
    localGovernments: [
      { id: 'binji', name: 'Binji', code: 'BIN' },
      { id: 'bodinga', name: 'Bodinga', code: 'BOD' },
      { id: 'dange-shuni', name: 'Dange Shuni', code: 'DAN' },
      { id: 'gada', name: 'Gada', code: 'GAD' },
      { id: 'goronyo', name: 'Goronyo', code: 'GOR' },
      { id: 'gudu', name: 'Gudu', code: 'GUD' },
      { id: 'gwadabawa', name: 'Gwadabawa', code: 'GWA' },
      { id: 'illela', name: 'Illela', code: 'ILL' },
      { id: 'isa', name: 'Isa', code: 'ISA' },
      { id: 'kebbe', name: 'Kebbe', code: 'KEB' },
      { id: 'kware', name: 'Kware', code: 'KWA' },
      { id: 'rabah', name: 'Rabah', code: 'RAB' },
      { id: 'sabon-birni', name: 'Sabon Birni', code: 'SAB' },
      { id: 'shagari', name: 'Shagari', code: 'SHA' },
      { id: 'silame', name: 'Silame', code: 'SIL' },
      { id: 'sokoto-north', name: 'Sokoto North', code: 'SON' },
      { id: 'sokoto-south', name: 'Sokoto South', code: 'SOS' },
      { id: 'tambuwal', name: 'Tambuwal', code: 'TAM' },
      { id: 'tangaza', name: 'Tangaza', code: 'TAN' },
      { id: 'tureta', name: 'Tureta', code: 'TUR' },
      { id: 'wamako', name: 'Wamako', code: 'WAM' },
      { id: 'wurno', name: 'Wurno', code: 'WUR' },
      { id: 'yabo', name: 'Yabo', code: 'YAB' }
    ]
  },
  {
    id: 'taraba',
    name: 'Taraba',
    code: 'TA',
    localGovernments: [
      { id: 'ardo-kola', name: 'Ardo Kola', code: 'ARD' },
      { id: 'bali', name: 'Bali', code: 'BAL' },
      { id: 'donga', name: 'Donga', code: 'DON' },
      { id: 'gashaka', name: 'Gashaka', code: 'GAS' },
      { id: 'gassol', name: 'Gassol', code: 'GAS' },
      { id: 'ibi', name: 'Ibi', code: 'IBI' },
      { id: 'jalingo', name: 'Jalingo', code: 'JAL' },
      { id: 'karim-lamido', name: 'Karim Lamido', code: 'KAR' },
      { id: 'kurmi', name: 'Kurmi', code: 'KUR' },
      { id: 'lau', name: 'Lau', code: 'LAU' },
      { id: 'sardauna', name: 'Sardauna', code: 'SAR' },
      { id: 'takum', name: 'Takum', code: 'TAK' },
      { id: 'ussa', name: 'Ussa', code: 'USS' },
      { id: 'wukari', name: 'Wukari', code: 'WUK' },
      { id: 'yorro', name: 'Yorro', code: 'YOR' },
      { id: 'zing', name: 'Zing', code: 'ZIN' }
    ]
  },
  {
    id: 'yobe',
    name: 'Yobe',
    code: 'YO',
    localGovernments: [
      { id: 'bade', name: 'Bade', code: 'BAD' },
      { id: 'bursari', name: 'Bursari', code: 'BUR' },
      { id: 'damaturu', name: 'Damaturu', code: 'DAM' },
      { id: 'fika', name: 'Fika', code: 'FIK' },
      { id: 'fune', name: 'Fune', code: 'FUN' },
      { id: 'geidam', name: 'Geidam', code: 'GEI' },
      { id: 'gujba', name: 'Gujba', code: 'GUJ' },
      { id: 'gulani', name: 'Gulani', code: 'GUL' },
      { id: 'jakusko', name: 'Jakusko', code: 'JAK' },
      { id: 'karasuwa', name: 'Karasuwa', code: 'KAR' },
      { id: 'machina', name: 'Machina', code: 'MAC' },
      { id: 'nangere', name: 'Nangere', code: 'NAN' },
      { id: 'nguru', name: 'Nguru', code: 'NGU' },
      { id: 'potiskum', name: 'Potiskum', code: 'POT' },
      { id: 'tarmuwa', name: 'Tarmuwa', code: 'TAR' },
      { id: 'yunusari', name: 'Yunusari', code: 'YUN' },
      { id: 'yusufari', name: 'Yusufari', code: 'YUS' }
    ]
  },
  {
    id: 'zamfara',
    name: 'Zamfara',
    code: 'ZA',
    localGovernments: [
      { id: 'anka', name: 'Anka', code: 'ANK' },
      { id: 'bakura', name: 'Bakura', code: 'BAK' },
      { id: 'birnin-magaji-kiyaw', name: 'Birnin Magaji/Kiyaw', code: 'BIR' },
      { id: 'bukkuyum', name: 'Bukkuyum', code: 'BUK' },
      { id: 'bungudu', name: 'Bungudu', code: 'BUN' },
      { id: 'gummi', name: 'Gummi', code: 'GUM' },
      { id: 'gusau', name: 'Gusau', code: 'GUS' },
      { id: 'kaura-namoda', name: 'Kaura Namoda', code: 'KAU' },
      { id: 'maradun', name: 'Maradun', code: 'MAR' },
      { id: 'maru', name: 'Maru', code: 'MAR' },
      { id: 'shinkafi', name: 'Shinkafi', code: 'SHI' },
      { id: 'talata-mafara', name: 'Talata Mafara', code: 'TAL' },
      { id: 'chafe', name: 'Chafe', code: 'CHA' },
      { id: 'zurmi', name: 'Zurmi', code: 'ZUR' }
    ]
  }
];

export default NIGERIA_STATES;