export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  AuthOptions: undefined;
  Login: undefined;
  Signup: undefined;
  EmailSignUp: undefined;
  OtpVerification: undefined;
  OtpSuccess: undefined;
  ForgotPassword: undefined;
  ResetLink: undefined;
  ResetPassword: undefined;
  SetupStep1: undefined;
  SetupStep2: undefined;
  SetupStep3: undefined;
  Home: undefined;
  Orders: undefined;
  Store: undefined;
  Reports: undefined;
  Profile: undefined;
};